### ISSUE TITLE
Normalize directory path to forward slash in sourcemap source property

### ISSUE THREAD

**Issue by liy** [gruntjs/grunt-contrib-concat#110] opened 2014-10-22 09:07 UTC
Under windows, `sourcemap.js` produces: `sources:[ "..\\main.js"]`.

In this case, devtools cannot map it to the correct file. It could be the `path.relative` always returns backslash in windows.

**Comment by kirubasankars** [comment] 2015-02-02 22:00
Yes. I having the same issue. its windows only. when I track it down. I got a temporary fix.

node_modules\grunt-contrib-concat\tasks\lib\sourcemap.js

may be line number 96 :

SourceMapConcatHelper.prototype.addlines = function(src, filename) {
    var relativeFilename = path.relative(path.dirname(this.dest), filename);

TO

SourceMapConcatHelper.prototype.addlines = function(src, filename) {
    var relativeFilename = path.relative(path.dirname(this.dest), filename).replace(/\\/g,'/');

**Comment by XhmikosR** [comment] 2015-02-18 17:01
Duplicate of #95.

**Closed by XhmikosR** 2015-02-18 17:01 UTC
